### PR TITLE
clean up main.css; add basic styling to trainer and emergency pages

### PR DESCRIPTION
**Pull request by bchugg**
Deleted a lot of fluff from main.css that wasn't being used in our project. Made sections for each page. 

Added basic styling for trainer and emergency pages.

### CODE REVIEW

**Comment by angadkalra** [comment]
Do you want someone to hit merge on this or are you going to keep committing to this PR then hit merge at the end?

**Comment by bchugg** [comment]
Ah shoot, I was hoping @sikander-94 would merge it earlier after taking a look - but now there's conflicts. I'll set to resolving them tomorrow night, I imagine it's nothing major.

**Comment by sikander-94** [comment]
Oops I'm sorry I didnt realize you wanted me to merge the pull request

**Comment by bchugg** [comment]
All good, I'll clean it up and push again.

**Comment by bchugg** [comment]
@sikander-94 Okay conflicts resolved. Requesting to merge if all looks good to you. Summary of changes:
- Refactor main.css (threw away lots of code we weren't using)
- Add basic styling to emergency and trainer pages

**Pull request merged**
