### PR TITLE
Fully functional get help email mechanism

### PR DESCRIPTION
**Pull request by alfaeddie**
This includes the addition of the node mode 'nodemailer' and the updates to index.js, getHelpView and getHelpViewController that will send an email to the reciever address (in the index.js) with the details.

### CODE REVIEW

**Comment by bchugg** [comment]
Is this pull-request in addition to #23 ? Or does this include all the changes present in that?

**Comment by sikander-94** [comment]
Don't have any idea about the Node stuff honestly, so I think if you're confident it works then thats good for us! 

One thing about the getHelpView though: 

- You dont need to set ng-controller in the get help view cause the routing takes care of setting the correct controller. Could you just remove that and then we'll merge? :+1:

**Comment by sikander-94** [comment]
Oh also, I'd like to second Ben's question @alfaeddie

**Comment by alfaeddie** [comment]
This pull request includes stuff from the node one too, but looks like you guys merged both.

**Pull request merged**
